import { v2 as cloudinary } from "cloudinary";
import albumModel from "../models/albumModel.js";

// here also create three arrow function that will be addAlbum, listAlbum, removeAlbum

// addAlbum api
const addAlbum = async (req, res) => {
  try {
    // here we get the name , desc, bgColour, image , property from our req.body
    const name = req.body.name;
    const desc = req.body.desc;
    const bgColour = req.body.bgColour;
    const imageFile = req.file;
    // Now we have to upload this image in our cloudinary storage.
    const imageUpload = await cloudinary.uploader.upload(imageFile.path, {
      resource_type: "image",
    }); // using this line our image will store in cloudinary storage and we will get the response in this imageUplaod variable.

    const albumData = {
      // here we will add the name, desc, bgColour, image
      name,
      desc,
      bgColour,
      image: imageUpload.secure_url,
      // so we have create albumData , next we will store the album data in the mongodb
    };
    // store data in mongodb
    const album = albumModel(albumData);
    await album.save(); // using this statement our album data will save in db

    // after that we will create one response
    res.json({ success: true, message: "Album added" });
  } catch (error) {
    res.json({ success: fetch });
  }
};
// **********************************  listAlbum *********************************

// listAlbum api
const listAlbum = async (req, res) => {
  // using this listAlbum API we can get all the album data in a single array.
  try {
    const allAlbums = await albumModel.find({}); //in this one we will store the all data
    // generate response
    res.json({ success: true, albums: allAlbums });
  } catch (error) {
    res.json({ success: false });
  }
  // so here we will create the API  for listAlbum
};

// removeAlbum
const removeAlbum = async (req, res) => {
  try {
    await albumModel.findByIdAndDelete(req.body.id); // in this 'findByIdAndDelete()' we provide album id auto generated by mongoDB so we get the id from req.body.id, and after excuting this statement our data will remove from mongoDB

    res.json({ success: true, message: "Album removed" });
  } catch (error) {
    res.json({ success: false });
  }
};

export { addAlbum, listAlbum, removeAlbum };
